### PR TITLE
Create config class for having a single declaration of each services

### PR DESCRIPTION
**Pull request by jefBinomed**
Create a config class for having a single declaration of each UUID

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
`formatUUID` is missing with this refactoring ;(

**Comment by jefBinomed** [comment]
Modification done ;)

**Comment by beaufortfrancois** [comment]
I'm not a huge fan of having a separate `Object` for the config to be honest.
What are the use cases for reusing this config in a "Get Started" app? The goal here is to quickly get you to connect to and interact with your BLE device.

**Comment by jefBinomed** [comment]
The generator can be use for me for something else than a "Get Started App" so when we want to go further in the developpement of our application  or if we change the UUID, we just do the change in one place.

**Comment by beaufortfrancois** [comment]
As discussed offline, closing this for now.

**Pull request closed without merging**
